### ISSUE TITLE
Proposal appears multiple times 

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/votebot#130]
I'm seeing my latest proposal multiple times on the proposals page at the moment - see screenshot below.

This is in Chrome on Android.

![screenshot_20170406-181244](https://cloud.githubusercontent.com/assets/136342/24767124/d5a8579a-1af5-11e7-9d00-1dbd5bef5560.png)

**Comment by Floppy** [comment]
Yeah, I've got that in #128 - been meaning to fix it for a few days - sorry! Will do so soon.

**Comment by Floppy** [comment]
Fortunately it's not having any real underlying effect, just looks very odd.

**Comment by philipjohn** [comment]
Ohhh yes. Should have searched!

**Comment by Floppy** [comment]
This should be fixed now, I hope, but deployments need new stuff enabling to handle job queueing:

* 1 worker dyno enabled
* heroku redis (hobby dev is fine) addon
