### ISSUE TITLE
Rejected comment text is incomplete

### ISSUE THREAD

**Issue by geeksareforlife** [openpolitics/votebot#185]
When votebot closes a PR as age exceeded, the comment it leaves seems to be:

"Closed automatically: maximum age exceeded. Please feel free to resubmit this as a new proposal, however, based on the current text."

(see https://votebot.openpolitics.org.uk/proposals/496)

Doesn't exactly make much sense!

**Comment by Floppy** [comment]
Oops - I wrote that and it makes sense *to me*, but obviously not to other people. What do you reckon it should say, or what's the confusing part?

**Comment by geeksareforlife** [comment]
Looks to be here that needs changing:

https://github.com/openpolitics/votebot/blob/master/app/models/concerns/github_pull_request.rb#L70

Not sure what we want it to actually say - there is clearly something intended to come after that

**Comment by geeksareforlife** [comment]
oh, your comment popped up at the same time!

So the first statement makes sense, it is the "however, based on the current text" that doesn't make sense to me - it looks like there should be more to that sentence.

What is it you are trying to say?

**Comment by Floppy** [comment]
OK, yeah. I'm trying to say that the base text has probably changed, so go back to the current version and submit your change using the new text as the original. It's a bit tortuous, suggestions definitely appreciated! Maybe it doesn't need saying at all.

**Comment by Floppy** [comment]
I want to encourage resubmission, because often propsals die simply because they lose momentum. Maybe it would be more helpful to link to an editor for a fresh version, or something.

**Comment by geeksareforlife** [comment]
Ah, I see.  So maybe:

Closed automatically: maximum age exceeded. Please feel free to resubmit this as a new proposal, but remember you will need to base any new proposal on the current policy text."

**Comment by Floppy** [comment]
That's a lot better, yeah. Want to pop it in a PR?

**Comment by geeksareforlife** [comment]
Will do

**Comment by geeksareforlife** [comment]
Thank you, I see you merged #186 but I failed to put a fixes message in, so will close this now
