### ISSUE TITLE
Show full context for vote

### ISSUE THREAD

**Issue by Floppy** [openpolitics/votebot#24]
Show comments, votes, and the change itself directly in the votebot, so that we can customise the presentation rather than just relying on the GitHub PR interface.

**Comment by Floppy** [comment]
I had a thought on this, to render it in a kind of chat-bubble type interface to show the back and forth more easily. Also, we can store all comments in a big text blob locally. Also easy to show votes in more detail. This may move out of my head into reality soon, now I'm thinking about it.

**Comment by Floppy** [comment]
To start with, "add comment" can just link to the PR, but it should be easy to use the API to add one directly.

**Comment by Floppy** [comment]
Playing about, have made this:

<img width="1167" alt="screen shot 2017-02-22 at 00 09 35" src="https://cloud.githubusercontent.com/assets/3565/23191006/481d576a-f893-11e6-842a-f8e4152c2fa8.png">

**Comment by Floppy** [comment]
@philipjohn whatcha reckon? First stab, but I quite like it.

**Comment by philipjohn** [comment]
It's great!

**Comment by Floppy** [comment]
Another improvement, getting merged in soon:

<img width="982" alt="screen shot 2017-02-25 at 15 28 47" src="https://cloud.githubusercontent.com/assets/3565/23332292/2c013838-fb6f-11e6-97b5-6f5981054a67.png">
