### ISSUE TITLE
Main brand title is not settable by user

### ISSUE THREAD

**Issue by Floppy** [openpolitics/votebot#82]
Allow user to set a brand title, link and image via the env vars. See https://labour-votebot.herokuapp.com/ for an example.

**Comment by Floppy** [comment]
This now works. You set the environment variables:

* PROJECT_NAME: the brand text
* PROJECT_URL: the brand link

And optionally, some images:

* PROJECT_LOGO
* FAVICON_URL

@philipjohn you'll want to do this for the field guide deployment, I expect. I don't have access I don't think.

**Comment by philipjohn** [comment]
Ohhh it's on my personal Heroku... I'll move it ☺️
